### ISSUE TITLE
Cannot find module "@framer/lintonye.parallax/code/Parallax"

### ISSUE THREAD

**Issue by RustyDev** [lintonye/parallax#2]
This is throwing an error when using the component in a fresh project.

```javascript
import {
    scrollOverrides,
    modulate,
    speed,
    sticky,
} from "@framer/lintonye.parallax/code/Parallax"
```

`Cannot find module "@framer/lintonye.parallax/code/Parallax"`

I also downloaded the [example project](https://www.dropbox.com/s/6tpjipqxyftbz1v/parallax-webinar.framerx?dl=0
) and see the same issue.

I'm using Framer X library version 1.0.17

**Comment by skynet01** [comment]
Same, any update on this? Looks like it would be an easy fix

**Comment by lintonye** [comment]
This package only works for Framer Library 0.10. Will update it to the latest version a bit later!

**Comment by skynet01** [comment]
Thanks for the update! I tried for an hour to get it to work, until I realized that api is outdated 😂

**Comment by lintonye** [comment]
The package has been updated in Oct 2019. The latest version (1.52) should work with the latest version of Framer.
